debug: true
server:
  port: 8080
  servlet:
    context-path: /
     
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
         facebook:
          clientId: 809669730709452
          clientSecret: 56ca49979da9d04a0e445588042653ab
          scope:
           - email
           - public_profile
         # 沒有指定 scope 的話, 預設拿到的是 DefaultOidcUser , 無法被轉型為 CustomOAuth2User
         google:
           clientId: your-client-id
           clientSecret: your-client-secret
           scope:
             - email
             - profile